version: '3'
services:
  test:
    image: openjdk:17.0.2-slim
    working_dir: /api-service
    command: ./gradlew clean build
    environment:
      GITHUB_USERNAME: ${GITHUB_USERNAME}
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      SEMANTIC_VERSION: ${SEMANTIC_VERSION}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - gradle-cache:/root/.gradle
  publish:
    image: openjdk:17.0.2-slim
    working_dir: /api-service
    command: ./gradlew clean bootJar publish
    environment:
      GITHUB_USERNAME: ${GITHUB_USERNAME}
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      SEMANTIC_VERSION: ${SEMANTIC_VERSION}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - gradle-cache:/root/.gradle
volumes:
  gradle-cache:
    external: true
