steps:
  - label: ":white_check_mark: Unit test"
    key: test
    command: docker-compose run test
    artifact_paths:
      - "build/check-reports/*"
  - label: ":maven: Publish Maven artifact to GitHub registry"
    depends_on: test
    command:
      - docker-compose run publish
